// FILE IS GENERATED FROM docs/winmux-*.adoc files
// TO REGENERATE THE FILE RUN generate.sh

let subcommandDescriptions = [
    ["  agent", "Query, validate, and apply agent-oriented window layout JSON"],
    ["  balance-sizes", "Balance sizes of all windows in the current tab"],
    ["  close-all-windows-but-current", "On the focused tab, close all windows but current"],
    ["  close", "Close the focused window"],
    ["  config", "Query WinMux config options"],
    ["  debug-windows", "Interactive command to record Accessibility API debug information to create bug reports"],
    ["  enable", "Temporarily enable or disable WinMux"],
    ["  flatten-tab-tree", "Flatten the tree of the focused tab"],
    ["  flatten-workspace-tree", "Legacy alias for flatten-tab-tree"],
    ["  folder", "Legacy alias for project"],
    ["  focus-back-and-forth", "Switch between the current and previously focused elements back and forth"],
    ["  focus-monitor", "Focus monitor by relative direction, by order, or by pattern"],
    ["  focus", "Set focus to a window."],
    ["  fullscreen", "Toggle the fullscreen mode for the focused window"],
    ["  join-with", "Put the focused window and the nearest node in the specified direction under a common parent container"],
    ["  layout", "Change layout of the focused window to the given layout"],
    ["  list-apps", "Print the list of running applications that appears in the Dock and may have a user interface"],
    ["  list-exec-env-vars", "List environment variables that exec-* commands and callbacks are run with"],
    ["  list-modes", "Print a list of modes currently specified in the configuration"],
    ["  list-monitors", "Print monitors that satisfy conditions"],
    ["  list-windows", "Print windows that satisfy conditions"],
    ["  list-tabs", "Print tabs that satisfy conditions"],
    ["  list-workspaces", "Legacy alias for list-tabs"],
    ["  macos-native-fullscreen", "Toggle macOS fullscreen for the focused window"],
    ["  macos-native-minimize", "Minimize focused window"],
    ["  mode", "Activate the specified binding mode"],
    ["  move-mouse", "Move mouse to the requested position"],
    ["  move-node-to-monitor", "Move window to monitor targeted by relative direction, by order, or by pattern"],
    ["  move-node-to-folder", "Legacy alias for move-node-to-project"],
    ["  move-node-to-project", "Move the focused window to the specified project"],
    ["  move-node-to-tab", "Move the focused window to the specified tab"],
    ["  move-node-to-workspace", "Legacy alias for move-node-to-tab"],
    ["  move-tab-to-monitor", "Move tab to monitor targeted by relative direction, by order, or by pattern."],
    ["  move-workspace-to-monitor", "Legacy alias for move-tab-to-monitor"],
    ["  move", "Move the focused window in the given direction"],
    ["  new-tab", "Open a fresh empty tab on the focused monitor"],
    ["  project", "Focus the specified project"],
    ["  reload-config", "Reload currently active config"],
    ["  reorder-tab", "Reorder a tab before or after another tab"],
    ["  reorder-workspace", "Legacy alias for reorder-tab"],
    ["  resize", "Resize the focused window"],
    ["  split", "Split focused window"],
    ["  stack-with", "Put the focused window into the same window stack as the nearest window in the specified direction."],
    ["  subscribe", "Subscribe to WinMux events and receive notifications via socket"],
    ["  summon-tab", "Move the requested tab to the focused monitor."],
    ["  summon-workspace", "Legacy alias for summon-tab"],
    ["  swap", "Swaps the focused window with another window."],
    ["  trigger-binding", "Trigger WinMux binding as if it was pressed by user"],
    ["  volume", "Manipulate volume"],
    ["  tab-back-and-forth", "Switch between the focused tab and previously focused tab back and forth"],
    ["  tab", "Focus the specified tab"],
    ["  workspace-back-and-forth", "Legacy alias for tab-back-and-forth"],
    ["  workspace", "Legacy alias for tab"],
]
